import { NgModule } from '@angular/core';
import { MatToolbarModule,
         MatIconModule,
         MatButtonModule,
         MatMenuModule,
         MatSidenavModule,
         MatCardModule,
         MatDividerModule,
         MatExpansionModule,
         MatGridListModule,
         MatListModule,
         MatStepperModule,
         MatTabsModule,
         MatTreeModule,
         MatButtonToggleModule,
         MatBadgeModule,
         MatChipsModule,
         MatProgressSpinnerModule,
         MatProgressBarModule,
         MatSlideToggleModule,
         MatSliderModule,
         MatSelectModule,
         MatRadioModule,
         MatInputModule,
         MatFormFieldModule,
         MatDatepickerModule,
         MatCheckboxModule,
         MatAutocompleteModule} from '@angular/material';

const materalComponent = [
  MatToolbarModule,
  MatIconModule,
  MatButtonModule,
  MatMenuModule,
  MatSidenavModule,
  MatCardModule,
  MatDividerModule,
  MatExpansionModule,
  MatGridListModule,
  MatListModule,
  MatStepperModule,
  MatTabsModule,
  MatTreeModule,
  MatButtonToggleModule,
  MatBadgeModule,
  MatChipsModule,
  MatProgressSpinnerModule,
  MatProgressBarModule,
  MatSlideToggleModule,
  MatSliderModule,
  MatSelectModule,
  MatRadioModule,
  MatInputModule,
  MatFormFieldModule,
  MatDatepickerModule,
  MatCheckboxModule,
  MatAutocompleteModule,
];

@NgModule({
  exports: [materalComponent],
  imports: [materalComponent]
})
export class MaterialModule { }
